--DATA ANALYSIS--
-- 1. LIST THE FOLLOWING DETAILS OF EACH EMPLOYEE WITH THE FOLLOWING INFORMATION: EMPLOYEE NUMBER, LAST NAME, FIRST NAME, SEX AND SALARY
SELECT EMPLOYEES.EMP_NO, LAST_NAME, FIRST_NAME, SEX, SALARY
FROM EMPLOYEES
INNER JOIN SALARIES
ON EMPLOYEES.EMP_NO = SALARIES.EMP_NO

-- 2. LIST FIRST NAME, LAST NAME, AND HIRE DATE FOR EMPLOYEE NUMBES WHOE WERE HIRED IN 1986
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE
FROM EMPLOYEES 
INNER JOIN SALARIES
ON EMPLOYEES.EMP_NO = SALARIES.EMP_NO
WHERE HIRE_DATE BETWEEN '01/01/1986' AND '12/31/1986'

--3 LIST THE MANAGER OF EACH DEPARMENT OF EACH EMPLOYEE WITH THE FOLLOWING INFORMATION: EMPLOYEE NUMBER, LAST NAME, FIRST NAME AND DEPARTMENT NAME
SELECT DEPS.DEPT_NO, DEPS.DEPT_NAME, EMPLOYEES.EMP_NO, LAST_NAME, FIRST_NAME 
FROM DEPARTMENTS AS DEPS
INNER JOIN DEPT_MANAGER AS DEPM
ON DEPS.DEPT_NO = DEPM.DEPT_NO
INNER JOIN EMPLOYEES
ON DEPM.EMP_NO = EMPLOYEES.EMP_NO

--4 LIST THE DEPARMENT OF EACH EMPLOYEE WITH THE FOLLOWING INFORMATION: EMPLOYEE NUMBER, LAST NAME, FIRST NAME AND DEPARTMENT NAME
SELECT EMPLOYEES.EMP_NO, LAST_NAME, FIRST_NAME, DEPS.DEPT_NAME
FROM DEPARTMENTS AS DEPS
INNER JOIN DEPT_EMP AS DEPE
ON DEPS.DEPT_NO = DEPE.DEPT_NO
INNER JOIN EMPLOYEES
ON DEPE.EMP_NO = EMPLOYEES.EMP_NO

--5. LIST FIRST NAME, LAST NAME AND SEX WHOSE FIRST NAME IS HERCULES AND LAST NAMES BEGIN WITH "B"
SELECT FIRST_NAME, LAST_NAME, SEX
FROM EMPLOYEES
INNER JOIN DEPT_EMP AS DEPE
ON DEPE.EMP_NO = EMPLOYEES.EMP_NO
INNER JOIN DEPARTMENTS AS DEPS
ON DEPS.DEPT_NO = DEPE.DEPT_NO
WHERE FIRST_NAME LIKE 'Hercules' AND LAST_NAME LIKE 'B%'

--6 LIST ALL EMPLOYEES IN THE SALES DEPARMENT INCLUDING THEIER EMPLOYEE NUMBER, LAST NAME, FIRST NAME AND DEPARTMENT NAME
SELECT EMPLOYEES.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME, DEPS.DEPT_NAME 
FROM DEPARTMENTS AS DEPS
INNER JOIN DEPT_EMP AS DEPE
ON DEPS.DEPT_NO = DEPE.DEPT_NO
INNER JOIN EMPLOYEES
ON DEPE.EMP_NO = EMPLOYEES.EMP_NO
WHERE DEPS.DEPT_NAME ='Sales';

--7 LIST ALL EMPLOYEES IN THE SALES AND DEVELOPMENT DEPARMENT INCLUDING THEIR EMPLOYEE NUMBER, LAST NAME, FIRST NAME AND DEPARTMENT NAME
SELECT EMPLOYEES.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME, DEPS.DEPT_NAME 
FROM DEPARTMENTS AS DEPS
INNER JOIN DEPT_EMP AS DEPE
ON DEPS.DEPT_NO = DEPE.DEPT_NO
INNER JOIN EMPLOYEES
ON DEPE.EMP_NO = EMPLOYEES.EMP_NO
WHERE DEPS.DEPT_NAME IN ('Sales','Development')

--8. IN DESCENDING ORDER, LIST THE FREQUESNCY COUNT OF EMPLOYEE LAST NAMES, I.E, HOW MANY EMPLOYEES SHAE EACH LAST NAME
SELECT LAST_NAME, COUNT(lAST_NAME) 
FROM EMPLOYEES
GROUP BY LAST_NAME
ORDER BY LAST_NAME DESC;

--SELECT Count(LAST_NAME) FROM EMPLOYEES